accepts: ".*"
rejects: "empty|metadata/.*"

category: "Uncategorized"
config: {}
cpu_cores: 1
description: "ALv4 Service Example"
enabled: false
install_by_default: true
is_external: false
licence_count: 0

name: "ExampleService"
version: '0'

ram_mb: 1024

disable_cache: false

stage: "CORE"
submission_params: []
supported_platforms: ["linux"]
timeout: 60